[package]
name = "tms_internal_client"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "RPC client of TMS."
license = "Apache-2.0"
edition = "2018"


[features]
default = []
mesalock_sgx = ["sgx_tstd", "mesatee_core/mesalock_sgx", "tms_internal_proto/mesalock_sgx"]
cov = ["sgx_cov"]

[dependencies]
cfg-if       = { version = "0.1.9" }
serde        = { version = "1.0.92" }
serde_derive = { version = "1.0.92" }
serde_json   = { version = "1.0.39" }
net2         = { version = "0.2.33" }
log          = { version = "0.4.6" }

tms_internal_proto = { path = "../proto", optional = true}
mesatee_core    = { version = "0.1.0" }

sgx_cov   = { version = "0.1.0", optional = true }
sgx_tstd  = { version = "1.0.8", optional = true }
sgx_types = { version = "1.0.8" }
