[package]
name = "tdfs_enclave"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
edition = "2018"

[lib]
name = "tdfs_enclave"
crate-type = ["staticlib"]

[features]
default = []
mesalock_sgx = ["sgx_tstd", "mesatee_core/mesalock_sgx", "tdfs_internal_proto/mesalock_sgx", "tdfs_external_proto/mesalock_sgx", "tms_internal_proto/mesalock_sgx", "tms_internal_client/mesalock_sgx", "kms_proto/mesalock_sgx"]
cov = ["sgx_cov"]

[dependencies]
cfg-if              = { version = "0.1.9" }
lazy_static         = { version = "1.0.2", features = ["spin_no_std"] }
uuid                = { version = "0.7.4", features = ["v4"] }
log                 = { version = "0.4.6" }
env_logger          = { version = "0.7.1" }

mesatee_core        = { version = "0.1.0" }

tdfs_internal_proto = { path = "../internal/proto", optional = true }
tdfs_external_proto = { path = "../external/proto", optional = true }
tms_internal_client  = { path = "../../tms/internal/client", optional = true }
tms_internal_proto   = { path = "../../tms/internal/proto", optional = true }
kms_proto           = { path = "../../kms/proto", optional = true}


sgx_cov             = { version = "0.1.0", optional = true }
sgx_tstd            = { version = "1.0.9", features = ["net", "backtrace"], optional = true }
sgx_types           = { version = "1.0.9" }
