# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "teaclave_scheduler_service_enclave"
version = "0.5.1"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave Scheduler Service"
license = "Apache-2.0"
edition = "2021"

[lib]
name = "teaclave_scheduler_service_enclave"
crate-type = ["staticlib", "rlib"]

[features]
default = []
mesalock_sgx = [
  "teaclave_attestation/mesalock_sgx",
  "teaclave_proto/mesalock_sgx",
  "teaclave_binder/mesalock_sgx",
  "teaclave_rpc/mesalock_sgx",
  "teaclave_service_enclave_utils/mesalock_sgx",
  "teaclave_types/mesalock_sgx",
  "teaclave_config/mesalock_sgx",
  "teaclave_config/build_config",
]
cov = ["teaclave_service_enclave_utils/cov"]
enclave_unit_test = ["teaclave_binder/enclave_unit_test", "teaclave_test_utils/mesalock_sgx"]

[dependencies]
log           = { version = "0.4.17", features = ["release_max_level_info"] }
anyhow        = { version = "1.0.26" }
serde_json    = { version = "1.0.39" }
serde         = { version = "1.0.92", features = ["derive"] }
thiserror     = { version = "1.0.9" }
gbdt          = { version = "0.1.0", features = ["input", "enable_training"] }
uuid          = { version = "0.8.1", features = ["v4"] }

teaclave_attestation           = { path = "../../../attestation" }
teaclave_config                = { path = "../../../config" }
teaclave_proto                 = { path = "../../proto" }
teaclave_binder                = { path = "../../../binder" }
teaclave_rpc                   = { path = "../../../rpc" }
teaclave_service_enclave_utils = { path = "../../utils/service_enclave_utils" }
teaclave_types                 = { path = "../../../types" }
teaclave_test_utils            = { path = "../../../tests/utils", optional = true }

sgx_cov       = { version = "2.0.0", optional = true }

[target.'cfg(not(target_vendor = "teaclave"))'.dependencies]
sgx_types     = { version = "2.0.0" }
