[package]
name = "gen_linear_model"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
edition = "2018"

[dependencies]
mesatee_sdk = { path = "../../mesatee_sdk" }
lazy_static = { version = "1.3.0" }
serde_derive = { version = "1.0.92" }
serde_json = { version = "1.0.39" }
serde = { version = "1.0.92" }
