[workspace]

# every member should take its own line,
# and for those to exclude from cmake build, just append the '# ignore'
# annotation suffix
members = [
  "mesatee_config/config_gen",
  "tests/integration_test",
  "examples/private_join_and_compute",
  "examples/quickstart",
  "examples/image_resizing",
  "examples/online_decrypt",
  "examples/rsa_sign",
  "examples/py_matrix_multiply",
  "examples/py_file",
  "examples/py_logistic_reg",
  "examples/kmeans",
  "examples/logistic_reg",
  "examples/lin_reg",
  "examples/svm",
  "examples/gen_linear_model",
  "examples/gaussian_mixture_model",
  "examples/gaussian_processes",
  "examples/dbscan",
  "examples/neural_net",
  "examples/naive_bayes",
  "examples/gbdt",
  "mesatee_sdk", # ignore
  "mesatee_sdk/c_sdk", # ignore
  "mesatee_utils/protected_fs_rs", # ignore
  "mesatee_cli" # ignore
]

exclude = [
  "mesatee_core",
]

[patch.crates-io]
# mesatee_core
mesatee_core = { path = "./mesatee_core" }
mesatee_config = { path = "./mesatee_config" }
mesatee_sdk = { path = "./mesatee_sdk" }

# We cannot remove these crates, because proto crates depend on them
sgx_cov = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
