[package]
name = "teaclave_frontend_enclave"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "Teaclave Frontend enclave"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "teaclave_frontend_enclave"
crate-type = ["staticlib"]

[features]
default = []
mesalock_sgx = [
  "sgx_tstd",
  "teaclave_frontend_proto/mesalock_sgx",
  "teaclave_rpc/mesalock_sgx",
  "teaclave_ipc/mesalock_sgx",
  "teaclave_types/mesalock_sgx",
  "teaclave_attestation/mesalock_sgx",
  "teaclave_service_sgx_utils/mesalock_sgx",
  "teaclave_service_config/mesalock_sgx",
]
cov = ["sgx_cov"]

[dependencies]
cfg-if          = { version = "0.1.9" }
lazy_static     = { version = "1.0.2", features = ["spin_no_std"] }
log             = { version = "0.4.6" }
env_logger      = { version = "0.7.1" }
uuid            = { version = "0.7.4", features = ["v4"] }
rand            = { version = "0.7.0" }
anyhow       = { version = "1.0.26" }
rustls       = { version = "0.16.0", features = ["dangerous_configuration"] }
serde        = { version = "1.0.92" }

sgx_cov         = { version = "1.1.0", optional = true }
sgx_tstd        = { version = "1.1.0", features = ["net", "thread", "backtrace"], optional = true }
sgx_types       = { version = "1.1.0" }

teaclave_config         = { path = "../../../config" }
teaclave_rpc            = { path = "../../../rpc" }
teaclave_attestation    = { path = "../../../attestation" }
teaclave_ipc            = { path = "../../../ipc" }
teaclave_types          = { path = "../../../types" }
teaclave_frontend_proto = { path = "../proto", optional = true}
teaclave_service_sgx_utils  = { path = "../../../common/service_sgx_utils", optional = true }
teaclave_service_config = { path = "../../../common/service_config", optional = true }
