# Teaclave Runtime Config
#
# Note that this config is loaded at running time. We don't have to trust the
# content though. Maliciously crafted config from this file will not break data
# confidentiality/integrity.

[api_endpoints]
authentication = { listen_address = "0.0.0.0:7776" }
frontend = { listen_address = "0.0.0.0:7777" }

[internal_endpoints]
dbs  = { listen_address = "0.0.0.0:7778", advertised_address = "127.0.0.1:7778", inbound_services = ["frontend"] }
execution = { listen_address = "0.0.0.0:7989", advertised_address = "127.0.0.1:7989" }

[audit]
enclave_info = { path = "enclave_info.toml" }
auditor_signatures = [
    { path = "auditors/godzilla/godzilla.sign.sha256" },
    { path = "auditors/optimus_prime/optimus_prime.sign.sha256" },
    { path = "auditors/albus_dumbledore/albus_dumbledore.sign.sha256" },
]
