# Teaclave Runtime Config
#
# Note that this config is loaded at running time. We don't have to trust the
# content though. Maliciously crafted config from this file will not break data
# confidentiality/integrity.

[api_endpoints]
authentication = { listen_address = "0.0.0.0:7776" }
frontend = { listen_address = "0.0.0.0:7777" }

[internal_endpoints]
access_control = { listen_address = "0.0.0.0:7779", advertised_address = "localhost:7779" }
authentication = { listen_address = "0.0.0.0:17776", advertised_address = "localhost:17776", inbound_services = ["frontend"] }
management = { listen_address = "0.0.0.0:17777", advertised_address = "localhost:17777" }
storage = { listen_address = "0.0.0.0:7778", advertised_address = "localhost:7778", inbound_services = ["frontend", "management"] }
execution = { listen_address = "0.0.0.0:7989", advertised_address = "localhost:7989" }

[audit]
enclave_info = { path = "enclave_info.toml" }
auditor_signatures = [
    { path = "auditors/godzilla/godzilla.sign.sha256" },
    { path = "auditors/optimus_prime/optimus_prime.sign.sha256" },
    { path = "auditors/albus_dumbledore/albus_dumbledore.sign.sha256" },
]

[attestation]
algorithm = "sgx_epid"
url = "https://api.trustedservices.intel.com:443"
key = "00000000000000000000000000000000"
spid = "00000000000000000000000000000000"
