# Teaclave Build Config

# Service provider's root CA certificate to verify clients
sp_root_ca_cert = { path = "../keys/sp_root_ca_cert.pem" }

# Intel Attestation Service root CA certificate to verify attestation report
ias_root_ca_cert = { path = "../keys/ias_root_ca_cert.pem" }

# Auditors' public keys to verify their endorsement signatures
auditor_public_keys = [
    { path = "../keys/auditors/godzilla/godzilla.public.der" },
    { path = "../keys/auditors/optimus_prime/optimus_prime.public.der" },
    { path = "../keys/auditors/albus_dumbledore/albus_dumbledore.public.der"},
]

# RPC max message size
rpc_max_message_size = 409600
