[package]
name = "fns_proto"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "RPC protocol of FNS."
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = ["sgx_tstd"]
cov = ["sgx_cov"]

[dependencies]
cfg-if       = { version = "0.1.9" }
serde        = { version = "1.0.39" }
serde_derive = { version = "1.0.92" }

sgx_cov = { version = "0.1.0", optional = true }
sgx_tstd = { version = "1.0.8", optional = true }
