[package]
name = "teaclave_frontend"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "Teaclave Frontend"
license = "Apache-2.0"
build = "build.rs"
edition = "2018"

[dependencies]
sgx_types       = { version = "1.1.0" }
sgx_urts        = { version = "1.1.0" }

log             = { version = "0.4.6" }
env_logger      = { version = "0.7.1" }
threadpool      = { version = "1.0" }
anyhow       = { version = "1.0.26" }
teaclave_ipc = { path = "../../../ipc" }
teaclave_service_app_utils = { path = "../../../common/service_app_utils" }
teaclave_service_config = { path = "../../../common/service_config" }
teaclave_binder = { path = "../../../binder" }