# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "teaclave_client_sdk"
version = "0.6.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave Rust Client SDK"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
teaclave_types        = { path = "../../types", features = ["app"] }
teaclave_attestation  = { path = "../../attestation" }
teaclave_rpc          = { path = "../../rpc" }
teaclave_proto        = { path = "../../services/proto", features = ["app"]  }
anyhow                = { version = "1.0.26" }
url                   = { version = "2.1.1" }
serde_json            = { version = "1.0.39" }
serde                 = { version = "1.0.92" }
pem                   = { version = "0.7.0" }
libc                  = { version = "0.2.68" }
tokio                 = { version = "1.0", features = ["rt-multi-thread", "time", "macros"] }

[patch.crates-io]
h2                = { git = "https://github.com/hyperium/h2", tag = "v0.3.19" }
tonic             = { git = "https://github.com/apache/incubator-teaclave-crates" }

sgx_tprotected_fs = { path = "../../third_party/rust-sgx-sdk/sgx_protected_fs/tfs" }
sgx_types         = { path = "../../third_party/rust-sgx-sdk/sgx_types" }
